version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    # command: service sshd start
    volumes:
      - .:/data/db
    ports:
        - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
        - mongo